// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package integration

import (
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	//cmdable := ioc.InitRedis()
	//v := ioc.InitMiddlewares(cmdable)
	//db := ioc.InitDB()
	//userDao := dao.NewUserDao(db)
	//userCache := cache.NewUserCache(cmdable)
	//userRepository := repository.NewUserRepository(userDao, userCache)
	//userServiceV1 := service.NewUserService(userRepository)
	//codeCache := cache.NewCodeCache(cmdable)
	//codeRepository := repository.NewCodeRepository(codeCache)
	//smsService := ioc.InitSmsService()
	//codeServiceV1 := service.NewCodeService(codeRepository, smsService)
	//userHandler := web.NewUserHandler(userServiceV1, codeServiceV1)
	//engine := ioc.InitGin(v, userHandler)
	//return engine
	return nil
}
