services:
  mysql8:
    image: mysql:8.0.29
    restart: always
    command:
      #      - 加入参数，设置 binlog 和主节点
      - --default_authentication_plugin=mysql_native_password
      - --binlog-format=ROW
      - --server-id=1
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      #      设置初始化脚本
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      #      注意这里我映射为了 13316 端口
      - "13316:3306"

  redis:
    image: 'bitnami/redis:7.2'  #      8.0.29
    environment:
      - ALLOW_EMPTY_PASSWORD=yes  #      允许空密码
    ports:
      - '6379:6379'  #     注意这里我映射为了 6379 端口


  #     一直用不上，注释掉先
  etcd:
    image: 'bitnami/etcd:3.5'
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    ports:
      #      所以你要用 12379 端口来连接 etcd
      - 12379:2379

  mongo:
    image: mongo:6.0
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017