// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	repository2 "Book_Exp/webook/interactive/repository"
	cache2 "Book_Exp/webook/interactive/repository/cache"
	article3 "Book_Exp/webook/internal/events/article"
	"Book_Exp/webook/internal/repository"
	article2 "Book_Exp/webook/internal/repository/article"
	"Book_Exp/webook/internal/repository/cache"
	"Book_Exp/webook/internal/repository/dao"
	"Book_Exp/webook/internal/repository/dao/article"
	"Book_Exp/webook/internal/service"
	"Book_Exp/webook/internal/web"
	"Book_Exp/webook/internal/web/jwt"
	"Book_Exp/webook/ioc"
)

// Injectors from wire.go:

func InitWebServer() *App {
	cmdable := ioc.InitRedis()
	handler := jwt.NewRedisJWTHandler(cmdable)
	loggerV1 := ioc.InitLogger()
	v := ioc.InitMiddlewares(cmdable, handler, loggerV1)
	db := ioc.InitDB(loggerV1)
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewUserRepository(userDao, userCache)
	userServiceV1 := service.NewUserService(userRepository, loggerV1)
	codeCache := cache.NewCodeCache(cmdable)
	codeRepository := repository.NewCodeRepository(codeCache)
	smsService := ioc.InitSmsService(cmdable)
	codeServiceV1 := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userServiceV1, codeServiceV1, handler, loggerV1)
	wechatService := ioc.InitOAuth2WechatHandler(loggerV1)
	wechatHandlerConfig := ioc.NewWechatHandler()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, userServiceV1, wechatHandlerConfig, handler)
	articleDAO := article.NewArticleDao(db)
	articleRepository := article2.NewCacheArticleRepostiory(articleDAO, loggerV1)
	client := ioc.InitKafka()
	syncProducer := ioc.NewSyncProducer(client)
	producer := article3.NewKafkaProducer(syncProducer)
	articleService := service.NewArticleService(articleRepository, producer, loggerV1)
	articleHandler := web.NewArticleHandler(articleService, loggerV1)
	engine := ioc.InitGin(v, userHandler, oAuth2WechatHandler, articleHandler)
	interactiveDAO := dao.NewGormInteractiveDAO(db)
	redisInteractiveCache := cache2.NewRedisInteractiveCache(cmdable)
	interactiveRepository := repository2.NewInteractiveService(interactiveDAO, redisInteractiveCache, loggerV1)
	interactiveReadEventBatchConsumer := article3.NewInteractiveReadEventBatchConsumer(loggerV1, interactiveRepository, client)
	v2 := ioc.NewConsumer(interactiveReadEventBatchConsumer)
	app := &App{
		server:   engine,
		consumer: v2,
	}
	return app
}
