// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package startup

import (
	"Book_Exp/webook/interactive/grpc"
	"Book_Exp/webook/interactive/repository"
	"Book_Exp/webook/interactive/repository/cache"
	dao2 "Book_Exp/webook/interactive/repository/dao"
	"Book_Exp/webook/interactive/service"
	"Book_Exp/webook/internal/repository/dao"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitInteractiveService() service.InteractiveService {
	gormDB := InitTestDB()
	interactiveDAO := dao.NewGormInteractiveDAO(gormDB)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	loggerV1 := InitLog()
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	return interactiveService
}

func InitInteractiverGRPCService() *grpc.InteractiveServiceServer {
	gormDB := InitTestDB()
	interactiveDAO := dao.NewGormInteractiveDAO(gormDB)
	cmdable := InitRedis()
	interactiveCache := cache.NewRedisInteractiveCache(cmdable)
	loggerV1 := InitLog()
	interactiveRepository := repository.NewCachedInteractiveRepository(interactiveDAO, interactiveCache, loggerV1)
	interactiveService := service.NewInteractiveService(interactiveRepository, loggerV1)
	interactiveServiceServer := grpc.NewInteractiveServiceServer(interactiveService)
	return interactiveServiceServer
}

// wire.go:

var thirdProvider = wire.NewSet(InitRedis, InitTestDB, InitLog)

var interactiveSvcProvider = wire.NewSet(service.NewInteractiveService, dao2.NewGormInteractiveDAO, repository.NewCachedInteractiveRepository, cache.NewRedisInteractiveCache, dao.NewGormInteractiveDAO)
