// Code generated by MockGen. DO NOT EDIT.
// Source: E:\Book_Exp\webook\internal\failover\code.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockCodeServiceV1 is a mock of CodeServiceV1 interface.
type MockCodeServiceV1 struct {
	ctrl     *gomock.Controller
	recorder *MockCodeServiceV1MockRecorder
}

// MockCodeServiceV1MockRecorder is the mock recorder for MockCodeServiceV1.
type MockCodeServiceV1MockRecorder struct {
	mock *MockCodeServiceV1
}

// NewMockCodeServiceV1 creates a new mock instance.
func NewMockCodeServiceV1(ctrl *gomock.Controller) *MockCodeServiceV1 {
	mock := &MockCodeServiceV1{ctrl: ctrl}
	mock.recorder = &MockCodeServiceV1MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeServiceV1) EXPECT() *MockCodeServiceV1MockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockCodeServiceV1) Send(ctx context.Context, biz, phone string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, biz, phone)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockCodeServiceV1MockRecorder) Send(ctx, biz, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockCodeServiceV1)(nil).Send), ctx, biz, phone)
}

// Verify mocks base method.
func (m *MockCodeServiceV1) Verify(ctx context.Context, biz, phone, inputCode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Verify", ctx, biz, phone, inputCode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Verify indicates an expected call of Verify.
func (mr *MockCodeServiceV1MockRecorder) Verify(ctx, biz, phone, inputCode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Verify", reflect.TypeOf((*MockCodeServiceV1)(nil).Verify), ctx, biz, phone, inputCode)
}
