// Code generated by MockGen. DO NOT EDIT.
// Source: E:\Book_Exp\webook\internal\failover\user.go

// Package svcmocks is a generated GoMock package.
package svcmocks

import (
	domain "Book_Exp/webook/internal/domain"
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserServiceV1 is a mock of UserServiceV1 interface.
type MockUserServiceV1 struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceV1MockRecorder
}

// MockUserServiceV1MockRecorder is the mock recorder for MockUserServiceV1.
type MockUserServiceV1MockRecorder struct {
	mock *MockUserServiceV1
}

// NewMockUserServiceV1 creates a new mock instance.
func NewMockUserServiceV1(ctrl *gomock.Controller) *MockUserServiceV1 {
	mock := &MockUserServiceV1{ctrl: ctrl}
	mock.recorder = &MockUserServiceV1MockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceV1) EXPECT() *MockUserServiceV1MockRecorder {
	return m.recorder
}

// FindOrCreate mocks base method.
func (m *MockUserServiceV1) FindOrCreate(ctx context.Context, phone string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOrCreate", ctx, phone)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOrCreate indicates an expected call of FindOrCreate.
func (mr *MockUserServiceV1MockRecorder) FindOrCreate(ctx, phone interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOrCreate", reflect.TypeOf((*MockUserServiceV1)(nil).FindOrCreate), ctx, phone)
}

// Login mocks base method.
func (m *MockUserServiceV1) Login(ctx context.Context, email, password string) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", ctx, email, password)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockUserServiceV1MockRecorder) Login(ctx, email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockUserServiceV1)(nil).Login), ctx, email, password)
}

// Profile mocks base method.
func (m *MockUserServiceV1) Profile(ctx context.Context, id int64) (domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Profile", ctx, id)
	ret0, _ := ret[0].(domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Profile indicates an expected call of Profile.
func (mr *MockUserServiceV1MockRecorder) Profile(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Profile", reflect.TypeOf((*MockUserServiceV1)(nil).Profile), ctx, id)
}

// SignUp mocks base method.
func (m *MockUserServiceV1) SignUp(ctx context.Context, u domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignUp", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignUp indicates an expected call of SignUp.
func (mr *MockUserServiceV1MockRecorder) SignUp(ctx, u interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignUp", reflect.TypeOf((*MockUserServiceV1)(nil).SignUp), ctx, u)
}

// UpdateNonSensitiveInfo mocks base method.
func (m *MockUserServiceV1) UpdateNonSensitiveInfo(ctx context.Context, user domain.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateNonSensitiveInfo", ctx, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateNonSensitiveInfo indicates an expected call of UpdateNonSensitiveInfo.
func (mr *MockUserServiceV1MockRecorder) UpdateNonSensitiveInfo(ctx, user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateNonSensitiveInfo", reflect.TypeOf((*MockUserServiceV1)(nil).UpdateNonSensitiveInfo), ctx, user)
}
