// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: grpc.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UserSerivice_GetById_FullMethodName = "/UserSerivice/GetById"
)

// UserSeriviceClient is the client API for UserSerivice service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserSeriviceClient interface {
	GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*GetByIdResponse, error)
}

type userSeriviceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserSeriviceClient(cc grpc.ClientConnInterface) UserSeriviceClient {
	return &userSeriviceClient{cc}
}

func (c *userSeriviceClient) GetById(ctx context.Context, in *GetByIdRequest, opts ...grpc.CallOption) (*GetByIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetByIdResponse)
	err := c.cc.Invoke(ctx, UserSerivice_GetById_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserSeriviceServer is the server API for UserSerivice service.
// All implementations must embed UnimplementedUserSeriviceServer
// for forward compatibility.
type UserSeriviceServer interface {
	GetById(context.Context, *GetByIdRequest) (*GetByIdResponse, error)
	mustEmbedUnimplementedUserSeriviceServer()
}

// UnimplementedUserSeriviceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUserSeriviceServer struct{}

func (UnimplementedUserSeriviceServer) GetById(context.Context, *GetByIdRequest) (*GetByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetById not implemented")
}
func (UnimplementedUserSeriviceServer) mustEmbedUnimplementedUserSeriviceServer() {}
func (UnimplementedUserSeriviceServer) testEmbeddedByValue()                      {}

// UnsafeUserSeriviceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserSeriviceServer will
// result in compilation errors.
type UnsafeUserSeriviceServer interface {
	mustEmbedUnimplementedUserSeriviceServer()
}

func RegisterUserSeriviceServer(s grpc.ServiceRegistrar, srv UserSeriviceServer) {
	// If the following call pancis, it indicates UnimplementedUserSeriviceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UserSerivice_ServiceDesc, srv)
}

func _UserSerivice_GetById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserSeriviceServer).GetById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserSerivice_GetById_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserSeriviceServer).GetById(ctx, req.(*GetByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UserSerivice_ServiceDesc is the grpc.ServiceDesc for UserSerivice service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserSerivice_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UserSerivice",
	HandlerType: (*UserSeriviceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetById",
			Handler:    _UserSerivice_GetById_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
